name: 'self-paced-learning'

version: '3.8'

services:
  # Database (PostgreSQL)
  database:
    image: postgres:15
    container_name: postgres_db_self_paced_learning
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-app_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/development/Dockerfile
    container_name: laravel_app_self_paced_learning
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  # NGINX (Web Server)
  nginx:
    image: nginx:latest
    container_name: nginx_server_self_paced_learning
    restart: always
    ports:
      - "9012:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/development/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pgdata: